dataloaders:
  loaders:
    - name: my_data
      type: csv
      path: data.csv
      batch_size: 1000

metrics:
  processors:
    - name: completeness
      type: completeness
      columns:
        input: [name, age, score]
      include_per_column: true
      include_overall: true
      include_metadata: false
