# Set strict to true to turn warnings into errors to catch warnings within CI.
strict: false
use_directory_urls: false
validation:
  omitted_files: ignore
  absolute_links: warn
  unrecognized_links: ignore
  anchors: ignore
theme:
  name: material
  # By default, fonts are pulled from Google on the Internet. To support offline usage, this is
  # disabled.
  font: false
  # palette:
  #   scheme: slate
  #   primary: green
  #   accent: yellow
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/math-integral-box
    # GitHub specific.
    repo: fontawesome/brands/github
  favicon: static/math-integral-box.png
  mermaid:
    version: 9.4.0
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune

markdown_extensions:
  - abbr
  - admonition
  - github-callouts
  - footnotes
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - static/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Safenai/dqm-ml-workspace
plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.hooks:pre_build"
        on_page_markdown: "docs.hooks:page_markdown"
  - search
  - offline:
      enabled: !ENV [MKDOCS_MATERIAL_OFFLINE, false]
  - mermaid2:
      version: "9.4.0"
  - mkdocstrings:
      handlers:
        python:
          options:
            show_if_no_docstring: true
            show_signature_annotations: true
  # Autodoc configuration.
  # https://github.com/tlambert03/mkdocs-api-autonav#configuration
  - api-autonav:
      modules: [
        "packages/dqm-ml-core/src/dqm_ml_core/",
        "packages/dqm-ml-images/src/dqm_ml_images/",
        "packages/dqm-ml-job/src/dqm_ml_job/",
        "packages/dqm-ml-pytorch/src/dqm_ml_pytorch/",
      ]
  # mkdocs-jupyter must come after api-autonav to handle generated files correctly
  - mkdocs-jupyter
  # This plugin is used to validate URLs (including anchors).
  - htmlproofer:
      # This is not enabled by default because this requires network I/O, so it is inherently not
      # exactly reproducible. For larger projects, this can also slow local build times.
      validate_external_urls: !ENV [HTMLPROOFER_VALIDATE_EXTERNAL_URLS, false]
      enabled: !ENV [MKDOCS_HTMLPROOFER_ENABLED, false]
      raise_error: false
watch:
  # Watch directories to reload on changes to docstrings for mkdocstrings plugin.
  - "packages/dqm-ml-core/src/dqm_ml_core/"
  - "packages/dqm-ml-images/src/dqm_ml_images/"
  - "packages/dqm-ml-job/src/dqm_ml_job/"
  - "packages/dqm-ml-pytorch/src/dqm_ml_pytorch/"
  - "docs"
site_name: DQM-ML V2
copyright: Copyright &copy; SafenAI
# GitHub Specific Configuration.
repo_name: dqm-ml-workspace
repo_url: https://github.com/Safenai/dqm-ml-workspace
edit_uri: edit/main/docs/user_guide/docs/
nav:
  - Home: index.md
  - Concepts: formal_concepts.md
  - Getting Started:
    - Quick Start: quickstart.md
    - Why a dqm-ml V2: dqm-ml-v2.md
    - Overview: dqm-ml-overview.md
  - User Guide:
    - CLI Reference: cli.md
    - Configuration:
      - Overview: configuration/overview.md
      - Interfaces: configuration/interfaces.md
      - Processors: configuration/processors.md
      - Features: configuration/features.md
      - Metrics: configuration/metrics.md
      - Gap: configuration/gap.md
      - Data Selection: configuration/data_selection.md
      - Global: configuration/global.md
    - YAML Basics: yaml_basics.md
  - Metrics: 
    - Overview: metrics.md
    - Completeness : metrics/completeness.md
    - Diversity : metrics/diversity.md
    - Domain gap : metrics/domain_gap.md
    - Representativeness : metrics/representativeness.md
    - Visual features : metrics/visual_features.md
  - Tutorials and Examples:
    - Fictive Scenario:
      - Overview: examples/overview.md
      - Config by Metric:
        - Completeness: examples/scenario/completeness.md
        - Diversity: examples/scenario/diversity.md
        - Representativeness: examples/scenario/representativeness.md
        - Visual Features: examples/scenario/visual_features.md
        - Embeddings: examples/scenario/embeddings.md
      - Domain Gap:
        - With Split: examples/scenario/domain_gap_split.md
        - With Filter: examples/scenario/domain_gap_filter.md
        - With Split + Filter: examples/scenario/domain_gap_split_filter.md
      - Full Pipeline: examples/scenario/full_story.md
      - Notebook with run: examples/notebooks/scenario_individual_steps.ipynb
      - Notebook with classes: examples/notebooks/scenario_full_pipeline.ipynb
    - Industrial Scenario:
      - Overview: TBD2.md
      - Notebook: examples/notebooks/multiple_metrics_tests_v2.ipynb
  # TODO: Uncomment when this documentation exists
  #   - Welding Challenge: tutorials/welding_challenge.md
  - Developer Guide:
    - What to consider: developer.md
    - Contributing: contributing.md
    - Roadmap: ROADMAP.md
    - Packages:
      - Core: packages/dqm-ml-core.md
      - Job: packages/dqm-ml-job.md
      - Images: packages/dqm-ml-images.md
      - PyTorch: packages/dqm-ml-pytorch.md
      - CLI: packages/dqm-ml.md
    - Pytest Report: reports/pytest/pytest_report.html
    - Coverage: reports/htmlcov/coverage_report.html
    - Performance: TBD1.md

