pipeline_config:

  dataloaders:
    source_dataset:
      type: parquet
      path: data/merged_ds_V2.parquet
      batch_size: 10000
      memory_limit: 2GB
      threads: 4

  metrics_processor:

    representativeness:
      type: representativeness
      metrics: [chi-square, grte, shannon-entropy, kolmogorov-smirnov]

      input_columns: [pression_huile,niveau_huile,temperature_huile,regime_rotation_bp]

      output_features: None

      output_metrics:
        chi-quare: chi-square-{}
        grte: grte-{}
        shannon-entropy: shannon-entropy-{}
        kolmogorov-smirnov: kolmogorov-smirnov-{}

      distribution: normal
      bins: 10

  outputs:

    metrics:
      type: parquet
      path_pattern: res_dqm-ml_representativeness_full.parquet
      columns: []

