pipeline_config:

  dataloaders:
    source_dataset:
      type: parquet
      path: data/merged_ds_V2.parquet
      batch_size: 10000
      memory_limit: 2GB
      threads: 4

  metrics_processor:

    completeness:
      type: completeness
      
      input_columns: [pression_huile,niveau_huile,temperature_huile,regime_rotation_bp]

      output_features: None

  outputs:

    metrics:
      type: parquet
      path_pattern: res_dqm-ml_completness_full.parquet
      columns: []

