## Yaml pipeline configuration

---
# A really basic pipeline configuration
pipeline_config: 

  # Configuration for the data loader
  dataloaders:
    source_dataset:
      type: parquet
      path: data/large_test_2m.parquet
      batch_size: 50000
      memory_limit: 2GB
      threads: 4
    
  metrics_processor:

    # Representativeness (distribution fitting)
    representativeness:
      type: representativeness

      input_columns: [blur_score, contrast, quality_score] # As for all metrics we define the input columns we are processing

      metrics: [chi-square, grte, shannon-entropy, kolmogorov-smirnov]

      output_features:  None

      # List of output columns to compute associate to metric processor capabilities      
      # As for all Metrics, we can difine a dictionary between internal metric nam (here the metrics)
      # And define how many placeolder can be use in column name (here the column name for example)
      # TODO : not use currently
      output_metrics:  
        chi-quare: chi-square-{}
        grte: grte-{}
        shannon-entropy: shannon-entropy-{}
        kolmogorov-smirnov: kolmogorov-smirnov-{}

      distribution: normal  # ou uniform
      bins: 20
      distribution_params:  # optional : force mean/std and if uniform min/max
        # mean: 128.0
        # std: 50.0

  outputs :
      
    metrics:
      type: parquet 
      path_pattern: tests/outputs/representativeness.parquet
      columns: []
      
