name: CI

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
  workflow_dispatch:

permissions:
  contents: read
  

jobs:
  quality:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        nox-session: ["lint", "spell", "type_check", "complexity"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Install hunspell library
        run: sudo apt-get update && sudo apt-get install -y libhunspell-dev

      - name: Test with Nox
        run: uv run nox -s ${{ matrix.nox-session }}

  compatibility:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Compatibility with Nox
        run: TQDM_DISABLE=1 uv run nox -s compatibility-${{ matrix.python-version }}

  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Restore resnet from cache
        uses: actions/cache/restore@v4
        with:
          path: /home/runner/.cache/torch
          key: dqm-test-resnet

      - name: Test with Nox
        run: TQDM_DISABLE=1 uv run nox -s test-${{ matrix.python-version }}

      - uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: docs/reports/pytest
          retention-days: 1
          overwrite: true

      - uses: actions/upload-artifact@v4
        with:
          name: pytest-coverage
          path: docs/reports/htmlcov
          retention-days: 1
          overwrite: true

      - name: Update cache containing resnet
        uses: actions/cache/save@v4
        if: always()
        with:
          path: /home/runner/.cache/torch
          key: dqm-test-resnet

  pages:
    runs-on: ubuntu-24.04
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - uses: actions/download-artifact@v4
        with:
          name: pytest-results
          path: docs/reports/pytest

      - uses: actions/download-artifact@v4
        with:
          name: pytest-coverage
          path: docs/reports/htmlcov

      - name: Publish Docs
        run: uv run nox -s docs_github_pages


