name: CI

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

env:
  UV_VERSION: "0.8.17"

jobs:
  quality:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        nox-session: ["lint", "type_check"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Test with Nox
        run: uv run nox -s ${{ matrix.nox-session }}

  container:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false

      - name: Validate build configuration
        uses: docker/build-push-action@v6
        with:
          call: check
          context: .
          file: ./Dockerfile

      - name: Build Container Image
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: ./Dockerfile
