name: Tests

# TODO: Move back to ci.yml with branch main once LFS quota reset
on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

env:
  UV_VERSION: "0.8.17"

jobs:
  compatibility:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # dqml v1 requires python >= 3.11
        # 3.11: ImportError: cannot import name 'override' from 'typing'
        python-version: [ "3.12", "3.13" ]
        # python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false

      - name: Create Git LFS file list
        run: git lfs ls-files -l |cut -d' ' -f1 |sort >.git/lfs-hashes.txt

      - name: Restore Git LFS object cache
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfsdata-v1-${{ hashFiles('.git/lfs-hashes.txt') }}
          restore-keys: |
            ${{ runner.os }}-lfsdata-v1-
            ${{ runner.os }}-lfsdata

      - name: Fetch any needed Git LFS objects and prune extraneous ones
        run: git lfs fetch --prune

      - name: Check out Git LFS content
        run: git lfs checkout

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Compatibility with Nox
        run: uv run nox -s compatibility-${{ matrix.python-version }}  

  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false

      - name: Create Git LFS file list
        run: git lfs ls-files -l |cut -d' ' -f1 |sort >.git/lfs-hashes.txt

      - name: Restore Git LFS object cache
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfsdata-v1-${{ hashFiles('.git/lfs-hashes.txt') }}
          restore-keys: |
            ${{ runner.os }}-lfsdata-v1-
            ${{ runner.os }}-lfsdata

      - name: Fetch any needed Git LFS objects and prune extraneous ones
        run: git lfs fetch --prune

      - name: Check out Git LFS content
        run: git lfs checkout

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Restore coco dataset from cache
        uses: actions/cache/restore@v4
        with:
          path: /home/runner/fiftyone
          key: dqm-test-coco-dataset

      - name: Restore resnet from cache
        uses: actions/cache/restore@v4
        with:
          path: /home/runner/.cache/torch
          key: dqm-test-resnet

      - name: Test with Nox
        run: uv run nox -s test-${{ matrix.python-version }}

      - name: Update cache containing coco dataset
        uses: actions/cache/save@v4
        if: always()
        with:
          path: /home/runner/fiftyone
          key: dqm-test-coco-dataset

      - name: Update cache containing resnet
        uses: actions/cache/save@v4
        if: always()
        with:
          path: /home/runner/.cache/torch
          key: dqm-test-resnet
